# Specifies Node Version 18.18.2 & Alpine Linux Version 3.18 OS
FROM node:18.18.2-alpine3.18

# Application Container Root Directory
WORKDIR /app

# install pnpm globally inside container only
RUN npm install -g pnpm

# Copy dependency version files first to utilize dockers layer dependency caching
COPY package.json pnpm-lock.yaml ./

# install dependencies
RUN pnpm install

# Copy everything from the current DIR to the container DIR
COPY . .

# Starts the project
CMD ["pnpm", "run", "dev"]

# Specifies the port the container listens to
EXPOSE 3000

LABEL org.opencontainers.image.description "LGT gridiron-survivor image for developer environment"