version: '3.8'

services:
  app-dev:
    image: ghcr.io/letsgettechnical/image:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  app-prod:
    image: ghcr.io/letsgettechnical/image:prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
