name: LGT Docker Build and Push Image

on:
    pull_request:
        branches: [develop]

jobs:
    build-and-push:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4.1.1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                  context: .
                  file: ./Dockerfile.dev
                  push: true
                  tags: ghcr.io/letsgettechnical/image:dev
  #A workflow is for testing
    jest-test:
        runs-on: ubuntu-latest

        strategy:
          matrix: 
            node-version: [20.x]

        steps: 
          - uses: actions/checkout@v4
          - uses: pnpm/action-setup@v2
            with:
              version: 8
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install
          - name: tests
            run: pnpm test   
#Playwright Testing
    playwright-test:
      timeout-minutes: 60000
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm ci
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
