name: LGT Jest & Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  jest-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APPWRITE_API_URL: ${{ secrets.NEXT_PUBLIC_APPWRITE_API_URL }}
      NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT_ID }}
      NEXT_PUBLIC_APPWRITE_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_DATABASE_ID }}
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v2.5
      - uses: pnpm/action-setup@v2.5
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      - name: tests
        run: pnpm test

  test-e2e-setup:
    name: Setup E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          max_timeout: 600
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"

  test_e2e:
    needs: test-e2e-setup
    name: Playwright Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APPWRITE_API_URL: ${{ secrets.NEXT_PUBLIC_APPWRITE_API_URL }}
      NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT_ID }}
      NEXT_PUBLIC_APPWRITE_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_APPWRITE_DATABASE_ID }}
    steps:
      - uses: actions/checkout@v2.5
      - uses: actions/setup-node@v2.5
        with:
          node-version: lts/*
      - run: npm install -g pnpm && pnpm install
      - run: pnpm exec playwright install --with-deps   
      - run: pnpm exec playwright test 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.5
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
