name: LGT Docker Build and Push Image

on:
    pull_request:
        branches: [develop]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4.1.1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                  context: .
                  file: ./Dockerfile.dev
                  push: true
                  tags: ghcr.io/letsgettechnical/image:dev
    tests:
        runs-on: ubuntu-latest

        strategy:
           matrix: 
            node-version: [21.x, 20.x]

        steps: 
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
          - name: npm install
            run: npm ci
         - name: tests
            run: npm test   
