name: LGT Docker Build and Push Image

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
    build-and-push:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4.1.1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                  context: .
                  file: ./Dockerfile.dev
                  push: true
                  tags: ghcr.io/letsgettechnical/image:dev
  #A workflow is for testing
    jest-test:
        runs-on: ubuntu-latest

        strategy:
          matrix: 
            node-version: [20.x]

        steps: 
          - uses: actions/checkout@v4
          - uses: pnpm/action-setup@v2
            with:
              version: 8
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install
          - name: tests
            run: pnpm test
  # Playwright Testing
    test_setup:
      name: Test setup
      runs-on: ubuntu-latest
      outputs:
        preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
      steps:
        - name: Wait for Vercel Preview
          uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
          id: waitForVercelPreviewDeployment
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            max_timeout: 600

    test_e2e:
      needs: test_setup
      name: Playwright Tests
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
        - name: Prepare testing env
          uses: actions/checkout@v4, actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Install dependencies
          run: npm install -g pnpm && pnpm install
        - name: Install Playwright Browsers
          run: pnpm exec playwright install --with-deps
        - name: Run Playwright tests
          run: pnpm exec playwright test
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30