name: LGT Docker Build and Push Image

on:
    pull_request:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4.1.1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.1.0
              with:
                  context: .
                  file: ./Dockerfile.dev
                  push: true
                  tags: ghcr.io/letsgettechnical/image:dev
